/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loja2;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author LUCAS
 */
public class PaginaInicial extends javax.swing.JFrame {

    public Connection con;
    
    public PaginaInicial() {
        initComponents();
        setLocationRelativeTo(null);
        setIcon();
    }
        
    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLLogo = new javax.swing.JLabel();
        jLLogo2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArquivo = new javax.swing.JMenu();
        jMIDesconectar = new javax.swing.JMenuItem();
        jMISair = new javax.swing.JMenuItem();
        jMLocação = new javax.swing.JMenu();
        jMIInserirAlterarExcluirLocacao = new javax.swing.JMenuItem();
        jMCliente = new javax.swing.JMenu();
        jMIInserir = new javax.swing.JMenuItem();
        jMIConsultar = new javax.swing.JMenuItem();
        jMIAlterarExcluir = new javax.swing.JMenuItem();
        jMVeiculos = new javax.swing.JMenu();
        jMIInserirExcluirMarcas = new javax.swing.JMenuItem();
        jMIInserirExcluirModelos = new javax.swing.JMenuItem();
        jMIInserirAlterarExcluirVeiculos = new javax.swing.JMenuItem();
        jMAjuda = new javax.swing.JMenu();
        jMISobre = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Página Inicial");
        setResizable(false);

        jLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loja2/LOGO1.png"))); // NOI18N

        jLLogo2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLLogo2.setForeground(new java.awt.Color(255, 153, 0));
        jLLogo2.setText("Locadora de Veículos");

        jMArquivo.setText("Arquivo");

        jMIDesconectar.setText("Desconectar");
        jMIDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDesconectarActionPerformed(evt);
            }
        });
        jMArquivo.add(jMIDesconectar);

        jMISair.setText("Sair");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMArquivo.add(jMISair);

        jMenuBar1.add(jMArquivo);

        jMLocação.setText("Locação");

        jMIInserirAlterarExcluirLocacao.setText("Inserir/Alterar/Excluir Locação");
        jMIInserirAlterarExcluirLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInserirAlterarExcluirLocacaoActionPerformed(evt);
            }
        });
        jMLocação.add(jMIInserirAlterarExcluirLocacao);

        jMenuBar1.add(jMLocação);

        jMCliente.setText("Cliente");

        jMIInserir.setText("Inserir Cliente");
        jMIInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInserirActionPerformed(evt);
            }
        });
        jMCliente.add(jMIInserir);

        jMIConsultar.setText("Consultar Clientes");
        jMIConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsultarActionPerformed(evt);
            }
        });
        jMCliente.add(jMIConsultar);

        jMIAlterarExcluir.setText("Alterar/Excluir Clientes");
        jMIAlterarExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlterarExcluirActionPerformed(evt);
            }
        });
        jMCliente.add(jMIAlterarExcluir);

        jMenuBar1.add(jMCliente);

        jMVeiculos.setText("Veículos");

        jMIInserirExcluirMarcas.setText("Inserir/Excluir Marcas");
        jMIInserirExcluirMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInserirExcluirMarcasActionPerformed(evt);
            }
        });
        jMVeiculos.add(jMIInserirExcluirMarcas);

        jMIInserirExcluirModelos.setText("Inserir/Excluir Modelos");
        jMIInserirExcluirModelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInserirExcluirModelosActionPerformed(evt);
            }
        });
        jMVeiculos.add(jMIInserirExcluirModelos);

        jMIInserirAlterarExcluirVeiculos.setText("Inserir/Alterar/Excluir Veículos");
        jMIInserirAlterarExcluirVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInserirAlterarExcluirVeiculosActionPerformed(evt);
            }
        });
        jMVeiculos.add(jMIInserirAlterarExcluirVeiculos);

        jMenuBar1.add(jMVeiculos);

        jMAjuda.setText("Ajuda");

        jMISobre.setText("Sobre");
        jMISobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISobreActionPerformed(evt);
            }
        });
        jMAjuda.add(jMISobre);

        jMenuBar1.add(jMAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLLogo2)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLLogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMISairActionPerformed

    private void jMIDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDesconectarActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMIDesconectarActionPerformed

    private void jMIConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsultarActionPerformed
        new ConsultarClientes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMIConsultarActionPerformed

    private void jMIInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInserirActionPerformed
        new Cliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMIInserirActionPerformed

    private void jMIAlterarExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlterarExcluirActionPerformed
        new Alterar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMIAlterarExcluirActionPerformed

    private void jMIInserirExcluirMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInserirExcluirMarcasActionPerformed
        new InserirMarca().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMIInserirExcluirMarcasActionPerformed

    private void jMIInserirExcluirModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInserirExcluirModelosActionPerformed
        new InserirAlterarModelo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMIInserirExcluirModelosActionPerformed

    private void jMIInserirAlterarExcluirVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInserirAlterarExcluirVeiculosActionPerformed
        new InserirAlterarExcluirVeiculo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMIInserirAlterarExcluirVeiculosActionPerformed

    private void jMIInserirAlterarExcluirLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInserirAlterarExcluirLocacaoActionPerformed
        new InserirAlterarExcluirLocacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMIInserirAlterarExcluirLocacaoActionPerformed

    private void jMISobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISobreActionPerformed
        JOptionPane.showMessageDialog(this, "Este software foi orgulhosamente criado por Lucas Lima.","Sobre",1);
    }//GEN-LAST:event_jMISobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLLogo2;
    private javax.swing.JMenu jMAjuda;
    private javax.swing.JMenu jMArquivo;
    private javax.swing.JMenu jMCliente;
    private javax.swing.JMenuItem jMIAlterarExcluir;
    private javax.swing.JMenuItem jMIConsultar;
    private javax.swing.JMenuItem jMIDesconectar;
    private javax.swing.JMenuItem jMIInserir;
    private javax.swing.JMenuItem jMIInserirAlterarExcluirLocacao;
    private javax.swing.JMenuItem jMIInserirAlterarExcluirVeiculos;
    private javax.swing.JMenuItem jMIInserirExcluirMarcas;
    private javax.swing.JMenuItem jMIInserirExcluirModelos;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenuItem jMISobre;
    private javax.swing.JMenu jMLocação;
    private javax.swing.JMenu jMVeiculos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LOGO1.png")));
    }
}
